on: [push, pull_request]

name: Build and Test

jobs:
  test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        dc: [ldc-latest, dmd-latest]
        os: [ubuntu-latest, macos-latest, windows-latest]
    if: ${{ !(matrix.os == "macos-latest" && matrix.dc == "dmd-latest") }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Build (Debug)
        run: dub build

      - name: Build (Release)
        run: dub build -b release

      - name: Test (Default)
        run: dub test